using Microsoft.AspNetCore.DataProtection.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using ogarniamy_zwierzaki_api.Animals;
using ogarniamy_zwierzaki_api.Auth;
using ogarniamy_zwierzaki_api.Documents;

namespace ogarniamy_zwierzaki_api.Data;

// Identity accounts, their sign-in sessions, data-protection keys, animals and documents. The naming convention is set where the context is configured.
// IdentityUserContext leaves out Identity's account-level roles: the product's roles are per animal (animal_members.role).
public sealed class AppDbContext(DbContextOptions<AppDbContext> options)
    : IdentityUserContext<AppUser>(options), IDataProtectionKeyContext
{
    // Read and written only through OwnedAnimals, which scopes every query to the current user.
    public DbSet<Animal> Animals => Set<Animal>();

    public DbSet<AnimalMember> AnimalMembers => Set<AnimalMember>();

    // Read and written only through OwnedDocuments, which reaches documents through the user's animal memberships.
    public DbSet<Document> Documents => Set<Document>();

    public DbSet<DocumentFile> DocumentFiles => Set<DocumentFile>();

    public DbSet<DataProtectionKey> DataProtectionKeys => Set<DataProtectionKey>();

    // Read and written only through DatabaseTicketStore, on behalf of the session cookie handler.
    public DbSet<AuthSession> AuthSessions => Set<AuthSession>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        // Identity sets explicit AspNet* table and index names, which the snake_case convention does not rename.
        builder.Entity<AppUser>(user =>
        {
            user.ToTable("users");
            user.HasIndex(u => u.NormalizedEmail).HasDatabaseName("ix_users_normalized_email");
            user.HasIndex(u => u.NormalizedUserName).HasDatabaseName("ix_users_normalized_user_name");
            // A preference only: losing the animal clears it instead of blocking the change.
            user.HasOne<Animal>().WithMany().HasForeignKey(u => u.LastCaptureAnimalId).OnDelete(DeleteBehavior.SetNull);
        });
        builder.Entity<IdentityUserClaim<string>>().ToTable("user_claims");
        builder.Entity<IdentityUserLogin<string>>().ToTable("user_logins");
        builder.Entity<IdentityUserToken<string>>().ToTable("user_tokens");

        builder.Entity<AuthSession>(session =>
        {
            session.ToTable(table =>
                table.HasCheckConstraint("ck_auth_sessions_expires_at", "expires_at > created_at"));
            session.HasKey(s => s.Id);
            // The key is generated by the ticket store, never by the database.
            session.Property(s => s.Id).ValueGeneratedNever();
            session.Property(s => s.Ticket).IsRequired();
            session.HasIndex(s => s.UserId);
            // A session cannot outlive its account.
            session.HasOne<AppUser>().WithMany().HasForeignKey(s => s.UserId).OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<Animal>(animal =>
        {
            animal.HasKey(a => a.Id);
            animal.Property(a => a.Name).HasMaxLength(Animal.NameMaxLength).IsRequired();
        });

        builder.Entity<AnimalMember>(member =>
        {
            member.ToTable(table => table.HasCheckConstraint("ck_animal_members_role", "role IN ('owner')"));
            member.HasKey(m => new { m.AnimalId, m.UserId });
            member.HasIndex(m => m.UserId);
            member.Property(m => m.Role)
                .HasConversion(role => ToDatabase(role), value => FromDatabase(value))
                .HasColumnType("text")
                .IsRequired();
            member.HasOne(m => m.Animal).WithMany().HasForeignKey(m => m.AnimalId);
            member.HasOne<AppUser>().WithMany().HasForeignKey(m => m.UserId);
        });

        builder.Entity<Document>(document =>
        {
            document.ToTable(table =>
            {
                table.HasCheckConstraint("ck_documents_storage_state", "storage_state IN ('uploading', 'stored')");
                // UploadedAt is set exactly when the capture is completed.
                table.HasCheckConstraint(
                    "ck_documents_uploaded_at",
                    "(storage_state = 'stored') = (uploaded_at IS NOT NULL)");
                table.HasCheckConstraint("ck_documents_capture_time_zone", "char_length(capture_time_zone) > 0");
            });
            document.HasKey(d => d.Id);
            // The operation ID is generated by the client, never by the database.
            document.Property(d => d.Id).ValueGeneratedNever();
            document.Property(d => d.CaptureTimeZone).HasMaxLength(Document.TimeZoneMaxLength).IsRequired();
            document.Property(d => d.StorageState)
                .HasConversion(state => ToDatabase(state), value => StorageStateFromDatabase(value))
                .HasColumnType("text")
                .IsRequired();
            // Serves the owner's per-animal list: Stored documents by EventDate, UploadedAt, then ID, all descending.
            document.HasIndex(d => new { d.AnimalId, d.StorageState, d.EventDate, d.UploadedAt, d.Id })
                .IsDescending(false, false, true, true, true);
            // The MVP never deletes animals or documents; Restrict keeps a stray delete from erasing originals.
            document.HasOne<Animal>().WithMany().HasForeignKey(d => d.AnimalId).OnDelete(DeleteBehavior.Restrict);
            document.HasMany(d => d.Files).WithOne().HasForeignKey(f => f.DocumentId).OnDelete(DeleteBehavior.Restrict);
        });

        builder.Entity<DocumentFile>(file =>
        {
            file.ToTable(table =>
            {
                // Per-row parts of the mode rule: one PDF, or up to ten JPEG/PNG images at positions 0-9.
                // Mixing and contiguous positions span rows and are enforced by OwnedDocuments.AddUploadAsync.
                table.HasCheckConstraint(
                    "ck_document_files_content_type",
                    $"content_type IN ('{DocumentFile.PdfContentType}', '{DocumentFile.JpegContentType}', " +
                    $"'{DocumentFile.PngContentType}')");
                table.HasCheckConstraint(
                    "ck_document_files_position",
                    $"position >= 0 AND position < {Document.MaxImageFiles} " +
                    $"AND (content_type <> '{DocumentFile.PdfContentType}' OR position = 0)");
                table.HasCheckConstraint(
                    "ck_document_files_byte_length", $"byte_length BETWEEN 1 AND {DocumentFile.MaxByteLength}");
                table.HasCheckConstraint("ck_document_files_sha256", "sha256 ~ '^[0-9a-f]{64}$'");
                table.HasCheckConstraint("ck_document_files_original_name", "char_length(original_name) > 0");
                // The key is derived from IDs only, so it can never carry a user-supplied file name.
                table.HasCheckConstraint(
                    "ck_document_files_blob_key",
                    "blob_key = 'documents/' || document_id::text || '/' || id::text");
                // A receipt is all-or-nothing and always matches the manifest.
                table.HasCheckConstraint(
                    "ck_document_files_receipt",
                    "(receipt_length IS NULL AND receipt_sha256 IS NULL AND receipt_etag IS NULL) " +
                    "OR (receipt_length = byte_length AND receipt_sha256 = sha256 AND receipt_etag IS NOT NULL)");
            });
            file.HasKey(f => f.Id);
            file.Property(f => f.OriginalName).HasMaxLength(DocumentFile.OriginalNameMaxLength).IsRequired();
            file.Property(f => f.ContentType).HasMaxLength(DocumentFile.ContentTypeMaxLength).IsRequired();
            file.Property(f => f.Sha256).HasMaxLength(DocumentFile.Sha256Length).IsRequired();
            file.Property(f => f.BlobKey).HasMaxLength(DocumentFile.BlobKeyMaxLength).IsRequired();
            file.Property(f => f.ReceiptSha256).HasMaxLength(DocumentFile.Sha256Length);
            file.Property(f => f.ReceiptEtag).HasMaxLength(DocumentFile.ReceiptEtagMaxLength);
            file.HasIndex(f => new { f.DocumentId, f.Position }).IsUnique();
            file.HasIndex(f => f.BlobKey).IsUnique();
        });
    }

    private static string ToDatabase(AnimalRole role) => role switch
    {
        AnimalRole.Owner => "owner",
        _ => throw new ArgumentOutOfRangeException(nameof(role), role, "Unknown animal role."),
    };

    private static AnimalRole FromDatabase(string value) => value switch
    {
        "owner" => AnimalRole.Owner,
        _ => throw new InvalidOperationException($"Unknown animal role '{value}'."),
    };

    private static string ToDatabase(DocumentStorageState state) => state switch
    {
        DocumentStorageState.Uploading => "uploading",
        DocumentStorageState.Stored => "stored",
        _ => throw new ArgumentOutOfRangeException(nameof(state), state, "Unknown document storage state."),
    };

    private static DocumentStorageState StorageStateFromDatabase(string value) => value switch
    {
        "uploading" => DocumentStorageState.Uploading,
        "stored" => DocumentStorageState.Stored,
        _ => throw new InvalidOperationException($"Unknown document storage state '{value}'."),
    };
}
